//-----------------------------------------------------------------
// All Rights Reserved. Copyright (c) 2026, DotNet.
//-----------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DotNet.Util
{
    /// <summary>
    /// 中文（简体）语言包，默认语言，其它语言缺键时回退到此包。
    /// 词条由 AppMessage.MsgXXXX 字段同步而来（共 248 条）。
    /// AppMessage 的静态字段本身保持不变（保证二进制兼容），字段值即本包的中文取值。
    /// 各语言包的键集合必须完全一致，由单元测试 MsgTests 断言校验。
    /// </summary>
    public static partial class MsgPack
    {
        private static Dictionary<string, string> ZhCnMessages()
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Common.ParameterRequired", "请输入{0}，不允许为空。" },
                { "Common.Success", "操作成功。" },
                { "Common.UnknownError", "发生未知错误。" },
                { "Common.Prompt", "提示信息" },
                { "System.DbConnectionFailed", "数据库连接不正常。" },
                { "System.WebServiceConnectionFailed", "WebService连接不正常。" },
                { "Common.NoDataModified", "无任何数据被修改。" },
                { "Common.RecordNotFound", "记录未找到，请检查网络连接，也可能数据已被其他人删除，请联系系统管理员核实。" },
                { "Common.DataChangedByOthers", "数据已被其他人修改，请按F5键重新更新取得数据。" },
                { "Validation.Duplicated", "{0}已重复。" },
                { "Result.AddSuccess", "新增成功。" },
                { "Result.UpdateSuccess", "更新成功。" },
                { "Result.SaveSuccess", "保存成功。" },
                { "Result.BatchSaveSuccess", "批量保存成功。" },
                { "Result.DeleteSuccess", "删除成功。" },
                { "Result.BatchDeleteSuccess", "批量删除成功。" },
                { "Confirm.Delete", "您确认删除吗？" },
                { "Confirm.DeleteItem", "您确认删除{0}吗？" },
                { "Common.RecordDeleteNotAllowed", "当前记录不允许被删除。" },
                { "Common.RecordItemDeleteNotAllowed", "当前记录{0}不允许被删除。" },
                { "Common.RecordEditNotAllowed", "当前记录不允许被编辑，请按F5键重新获得最新资料。" },
                { "Common.RecordItemEditNotAllowed", "当前记录{0}不允许被编辑，请按F5键重新获得最新资料。" },
                { "Common.IsFirstRecord", "当前记录已是第一条记录。" },
                { "Common.IsLastRecord", "当前记录已是最后一条记录。" },
                { "Validation.SelectAtLeastOne", "请至少选择一项{0}。" },
                { "Validation.NotGreaterThan", "{0}不能大于{1}。" },
                { "Validation.NotLessThan", "{0}不能小于{1}。" },
                { "Validation.CanNotEqual", "{0}不能等于 {1}。" },
                { "Validation.InvalidDate", "{0}不是有效的日期。" },
                { "Validation.InvalidChar", "{0}不是有效的字符。" },
                { "Validation.InvalidNumber", "{0}不是有效的数字。" },
                { "Validation.InvalidAmount", "{0}不是有效的金额。" },
                { "Validation.ContainsIllegalChar", "{0}名包含非法字符。" },
                { "Common.DataReferenced", "资料已经被引用，有关联资料在。" },
                { "Confirm.ForceDeleteReferenced", "资料已经被引用，有关联资料在，是否强制删除资料？" },
                { "Common.ChildNodeExists", "{0}有子节点不允许被删除，有子节点还未被删除。" },
                { "Common.MoveNotAllowed", "{0}不能移动到 {1}。" },
                { "Common.ChildNodeMoveNotAllowed", "{0}下的子节点不能移动到{1}。" },
                { "Confirm.Move", "确认移动{0}到{1}吗？" },
                { "Validation.NotEqual", "{0}不等于{1}。" },
                { "Common.ItemError", "{0}错误。" },
                { "Confirm.AuditPass", "确认审核通过吗？" },
                { "Confirm.AuditReject", "确认审核退回吗？" },
                { "Common.LockFailed", "不能锁定数据。" },
                { "Common.LockSuccess", "成功锁定数据。" },
                { "Confirm.SaveChangedData", "数据已经改变，想储存数据吗？" },
                { "Logon.PasswordCanNotRepeatInRecentTimes", "最近{0}次内密码不能重复。" },
                { "Logon.PasswordExpiredAccountLocked", "密码已过期，账号被锁定，请联系系统管理员。" },
                { "Logon.UserAlreadyOnline", "拒绝登录，用户已经在线。" },
                { "Logon.MacAddressNotAllowed", "拒绝登录，网卡Mac地址不符合限制条件。" },
                { "Logon.IpAddressRestricted", "拒绝登录，IP:{0}被限制访问,请联系系统管理人员。" },
                { "Logon.MaxOnlineUsersReached", "已到在线用户最大数量限制。" },
                { "Ip.InvalidIpFormat", "IP地址格式不正确。" },
                { "Ip.InvalidMacFormat", "MAC地址格式不正确。" },
                { "Ip.IpOrMacRequired", "请填写IP地址或MAC地址信息。" },
                { "Ip.DuplicateIpAddress", "存在相同的IP地址。" },
                { "Ip.AddSuccess", "IP地址新增成功。" },
                { "Ip.AddFailed", "IP地址新增失败。" },
                { "Ip.DuplicateMacAddress", "存在相同的MAC地址。" },
                { "Ip.MacAddSuccess", "MAC地址新增成功。" },
                { "Logon.CreateLoginAccountFirst", "请先新增该职员的登入系统用户信息。" },
                { "Ip.MacAddFailed", "MAC地址新增失败。" },
                { "Logon.PasswordNeverChanged", "请设定新密码，原始密码未曾修改过。" },
                { "Logon.PasswordNotChangedIn30Days", "请设定新密码，30天内未曾修改过密码。" },
                { "Validation.InvalidMinutes", "您输入的分钟数值不正确，请检查。" },
                { "Confirm.DiscardChangedData", "数据已经改变，不储存数据？" },
                { "Logon.PasswordChangeRequired", "请设定新密码，系统要求修改密码。" },
                { "Confirm.Remove", "您确认移除吗？" },
                { "Confirm.RemoveItem", "您确认移除{0}吗？" },
                { "Result.DeleteRecordsSuccess", "成功删除{0}条记录。" },
                { "Logon.UserAwaitingAudit", "用户登入被拒，用户审核中。" },
                { "Logon.UserLockedRetryAfterOneMinute", "用户被锁定，登入被拒绝，1分钟后登录或联系系统管理员。" },
                { "Logon.AccountNotActivatedPrompt", "用户账号未被激活，请及时激活用户账号。" },
                { "Logon.LockedNotBefore", "用户被锁定，登入被拒绝，不可早于：" },
                { "Logon.LockedNotAfter", "用户被锁定，登入被拒绝，不可晚于：" },
                { "Logon.LockedStartDate", "用户被锁定，登入被拒绝，锁定开始日期：" },
                { "Logon.LockedEndDate", "用户被锁定，登入被拒绝，锁定结束日期：" },
                { "Ip.IpAddressIncorrect", "IP Address 不正确。" },
                { "Ip.MacAddressIncorrect", "MAC Address 不正确。" },
                { "Logon.DuplicateLoginNotAllowed", "用户已经上线，不允许重复登入。" },
                { "Logon.PasswordIncorrect", "密码错误，登入被拒绝。" },
                { "Logon.OnlineUserLimitExceeded", "已超出用户在线数量上限：" },
                { "Logon.LoginDenied", "登入被拒绝。" },
                { "Common.AddPermissionItem", "新增操作权限项。" },
                { "Logon.StartTime", "登入开始时间" },
                { "Logon.EndTime", "登入结束时间" },
                { "Logon.PauseStartTime", "暂停开始时间" },
                { "Logon.PauseEndDate", "暂停结束日期" },
                { "Logon.UserOnlineDeleteNotAllowed", "{0}在在线，不允许删除。" },
                { "Logon.DeleteSelfNotAllowed", "目前用户{0}不允许删除自己。" },
                { "Logon.PasswordSequentialNotAllowed", "不允许使用连续重复密码。" },
                { "Confirm.ClearUserRole", "您确认清除用户角色关联吗？" },
                { "File.SelectedFileNotExists", "您选择的档案不存在，请重新选择。" },
                { "Confirm.MoveQuoted", "您确认移动 \"{0}\" 到 \"{1}\" 吗？" },
                { "Confirm.ExitApplication", "您确认退出应用程序吗？" },
                { "Confirm.OverwriteFile", "档案{0}已存在，要覆盖服务器上的档案吗？" },
                { "File.UploadSizeExceeded", "已经超过了上传限制，请检查要上传的档案大小。" },
                { "Confirm.DeleteImage", "您确认要删除图片吗？" },
                { "Validation.StartTimeAfterEndTime", "开始时间不能大于结束时间。" },
                { "Result.ClearSuccess", "清除成功。" },
                { "Result.ResetSuccess", "重置成功。" },
                { "Logon.TooManyPasswordAttempts", "已输入{0}次错误密码，不再允许继续登入，请重新启动程序进行登入。" },
                { "Common.QueryContent", "查询内容" },
                { "Validation.CodeTooLong", "编号总长度不要超过40位。" },
                { "Sequence.GenerateSuccess", "编号产生成功。" },
                { "Sequence.Increment", "增序列" },
                { "Sequence.Decrement", "减序列" },
                { "Sequence.Step", "步调" },
                { "Sequence.ResetSuccess", "序列重置成功。" },
                { "Confirm.ResetSequence", "您确认重置序列吗？" },
                { "Validation.UserNameRequired", "用户名称不允许为空，请输入。" },
                { "Common.NodeHasData", "目前节点上有资料。" },
                { "Common.DeleteSelfNotAllowed", "无法删除自己。" },
                { "Result.SetRelatedUserSuccess", "设置关联用户成功。" },
                { "Validation.CompanyRequired", "所在单位不允许为空，请选择。" },
                { "Result.ApplyAccountUpdateSuccess", "申请账号更新成功，请等待审核。" },
                { "Validation.PasswordMismatch", "密码不等于确认密码，请确认后重新输入。" },
                { "Common.UserFullName", "用户名称" },
                { "Common.RealName", "姓名" },
                { "Validation.InvalidEmail", "E-mail 格式不正确，请重新输入。" },
                { "Result.ApplyAccountSuccess", "申请账号成功，请等待审核。" },
                { "Confirm.OverwriteExportFile", "导出的目标文件已存在，要覆盖 \"{0}\" 吗？" },
                { "Result.SendEmailSuccess", "发送电子邮件成功。" },
                { "Result.ClearExceptionSuccess", "清除异常信息成功。" },
                { "Confirm.ClearException", "您确认清除异常信息吗？" },
                { "Validation.ContentRequired", "内容不能为空" },
                { "Result.SendEmailFailed", "发送电子邮件失败。" },
                { "Result.MoveSuccess", "移动成功。" },
                { "Common.ExceptionReport", "程序异常报告" },
                { "File.SelectedDocumentNotExists", "您选择的文档不存在，请重新选择。" },
                { "Common.NoDataToCopy", "没有要复制的数据！" },
                { "Validation.SelectDataRequired", "请选需要处理的数据。" },
                { "Confirm.NoRejectReason", "您确认不输入退回理由吗？" },
                { "Confirm.CancelWorkflow", "您确认撤销撤销审核流程中的单据吗？" },
                { "Validation.SelectAuditUser", "请选择提交给哪个用户审核。" },
                { "Confirm.SubmitToUser", "您确认提交给用户{0}审核吗？" },
                { "Workflow.SendSuccess", "工作流程发送成功。" },
                { "Workflow.SendFailed", "工作流程发送失败。" },
                { "Confirm.ReplaceFile", "您确认替换文件{0}吗？" },
                { "Org.ParentOrganization", "上级机构" },
                { "Confirm.SaveConfiguration", "已修改配置信息，需要保存吗？" },
                { "Common.NoDataToSave", "没有要保存的资料！" },
                { "Org.CompanyName", "单位名称" },
                { "Validation.SelectAuditDepartment", "请选择提交给哪个部门审核。" },
                { "Confirm.SubmitToDepartment", "您确认提交给部门{0}审核吗？" },
                { "Validation.SelectAuditRole", "请选择提交给哪个角色审核。" },
                { "Confirm.SubmitToRole", "您确认提交给角色{0}审核吗？" },
                { "Validation.SelectAuditor", "请选择提交给哪个角色或部门或人员审核。" },
                { "Workflow.RejectSuccess", "成功退回{0}项。" },
                { "Workflow.RejectFailed", "退回失败。" },
                { "Confirm.ForwardTo", "您确认要转发给{0}审核吗？" },
                { "Workflow.ForwardSuccess", "转发成功{0}项。" },
                { "Workflow.ForwardFailed", "转发失败。" },
                { "Logon.ForcedOfflineByOtherLogin", "下线通知，您的账号在另一地点登录，您被迫下线。" },
                { "Confirm.Save", "您确定保存吗？" },
                { "Common.Category", "分类。" },
                { "Validation.SelectItem", "请选择{0}。" },
                { "Validation.SelectUserOrgOrRole", "用户、组织机构、角色必须选择一个。" },
                { "Logon.AccountLockedForMinutes", "您的帐户登录异常，被系统锁定{0}分钟，若有疑问请联系系统管理员。" },
                { "Confirm.ClearPermission", "您确认清除权限吗？" },
                { "System.ConnectSuccess", "已经成功连接到目标数据。" },
                { "Common.DebugInfo", "调试信息" },
                { "System.AccessDenied", "访问被拒绝，未经授权的访问。" },
                { "System.ServiceCallDeniedNotSignedIn", "服务调用被拒绝，用户未登入。" },
                { "System.ConfigurationError", "系统设定讯息错误，请与软件开发商联系。" },
                { "Confirm.ResetMenu", "您确认重置功能选单吗？" },
                { "Validation.InvalidValue", "{0}不正确，请重新输入。" },
                { "Confirm.InitializeSystem", "您确认初始化系统吗？" },
                { "Common.Failed", "操作失败。" },
                { "Logon.PasswordStrengthInsufficient", "密码强度不符合要求，密码至少为8位数，且为数字加字母的组合。" },
                { "Common.Mobile", "手机号码" },
                { "Common.Email", "电子邮件" },
                { "Common.EmployeeNumber", "工号" },
                { "Logon.UserNameOrPasswordIncorrect", "用户名称或密码错误" },
                { "System.ServiceNotStarted", "服务未开始" },
                { "System.ServiceExpired", "服务过期" },
                { "Common.Value", "值" },
                { "Org.Company", "公司" },
                { "Org.Department", "部门" },
                { "Logon.EmailNotConfigured", "用户未设置电子邮件地址。" },
                { "Logon.AccountLockedRetryAfterOneMinute", "用户账号被锁定，1分钟后登录或联系系统管理员。" },
                { "Logon.AccountNotActivated", "用户还未激活账号。" },
                { "Logon.AccountAlreadyActivated", "用户账号已被激活。" },
                { "Common.UserRelation", "用户关联。" },
                { "Validation.ConstraintRequired", "请设置约束条件。" },
                { "Common.Show", "显示   ▽" },
                { "Common.Hide", "隐藏   △" },
                { "Result.ValidateExpressionSuccess", "验证表达式成功。" },
                { "Validation.ConditionRequired", "请输入条件。" },
                { "Validation.ContentEmpty", "请输入内容。" },
                { "Validation.MissingLeftBracket", "缺少（ 符号。" },
                { "Validation.MissingRightBracket", "缺少 ）符号。" },
                { "Common.UniqueUserName", "唯一用户名" },
                { "Common.Data", "资料" },
                { "Common.NoRecordMatched", "未找到满足条件的记录" },
                { "Common.UserName", "用户名" },
                { "Validation.DataError", "数据验证错误" },
                { "Common.NewPassword", "新密码" },
                { "Common.ConfirmPassword", "确认密码" },
                { "Common.OldPassword", "原密码" },
                { "Result.ModifySuccess", "修改{0}成功。" },
                { "Result.SetSuccess", "设置{0}成功。" },
                { "Common.Password", "密码" },
                { "Result.ExecuteSuccess", "执行成功。" },
                { "Logon.UserNotFoundCaseSensitive", "用户没有找到，请注意大小写。" },
                { "Logon.PasswordIncorrectCaseSensitive", "密码错误，请注意大小写。" },
                { "Logon.AccountDisabled", "登入被拒绝，帐户已被停用，请与系统管理员联系。" },
                { "Common.BaseCode", "基础编码" },
                { "Org.Employee", "职员" },
                { "Org.Organization", "组织机构" },
                { "Org.Role", "角色" },
                { "Common.Menu", "选单" },
                { "Common.Folder", "文件夹" },
                { "Common.Permission", "权限" },
                { "Common.PrimaryKey", "主键" },
                { "Common.Code", "编号" },
                { "Common.Name", "名称" },
                { "Common.ParentId", "父节点主键" },
                { "Common.ParentName", "父节点名称" },
                { "Common.FunctionCategoryId", "功能分类主键" },
                { "Common.UniqueId", "唯一识别主键" },
                { "Common.Subject", "主题" },
                { "Common.Content", "内容" },
                { "Common.StatusCode", "状态代码" },
                { "Common.Times", "次数" },
                { "Common.Enabled", "有效" },
                { "Common.Remark", "备注" },
                { "Common.SortCode", "排序码" },
                { "Common.CreatedBy", "建立者主键" },
                { "Common.CreatedOn", "建立时间" },
                { "Common.ModifiedBy", "最后修改者主键" },
                { "Common.ModifiedOn", "修改时间" },
                { "Common.Sort", "排序" },
                { "Common.Index", "索引" },
                { "Common.Field", "字段" },
                { "Common.Table", "数据表" },
                { "Common.Database", "数据库" },
                { "Logon.Relogin", "重新登入" },
                { "Validation.SelectAtLeastOneItem", "请至少选择一项。" },
                { "Validation.SelectOnlyOne", "只能选择一条数据。" },
                { "Sign.PrivateKey", "签名私钥。" },
                { "Sign.Password", "签名密码。" },
                { "Sign.CommunicationUserName", "通讯用户名称。" },
                { "Sign.CommunicationPassword", "通讯密码。" },
                { "Sign.VerificationCode", "验证码" },
                { "Enum.Status.SystemCodeError", "系统编号不正确，登录被阻止" },
                { "Enum.Status.AccessDeny", "未授权的访问，访问被阻止" },
                { "Enum.Status.DbError", "数据库连接错误" },
                { "Enum.Status.UserOnline", "用户已在线" },
                { "Enum.Status.UserNotLogin", "用户未登录" },
                { "Enum.Status.MissingData", "缺失用户登录数据" },
                { "Enum.Status.Error", "发生错误" },
                { "Enum.Status.Ok", "运行成功" },
                { "Enum.Status.OkAdd", "添加成功" },
                { "Enum.Status.CanNotLock", "不能锁定数据" },
                { "Enum.Status.LockOk", "成功锁定数据" },
                { "Enum.Status.OkUpdate", "更新数据成功" },
                { "Enum.Status.OkDelete", "删除成功" },
                { "Enum.Status.Exist", "数据已重复,不可以重复" },
                { "Enum.Status.ErrorCodeExist", "编号已存在,不可以重复" },
                { "Enum.Status.ErrorNameExist", "名称已重复" },
                { "Enum.Status.ErrorValueExist", "值已重复" },
                { "Enum.Status.ErrorUserExist", "用户名已重复" },
                { "Enum.Status.OkOperation", "操作成功" },
                { "Enum.Status.ErrorDataRelated", "数据已经被引用，有关联数据在" },
                { "Enum.Status.ErrorDeleted", "数据已被其他人删除" },
                { "Enum.Status.ErrorUpdate", "更新数据失败" },
                { "Enum.Status.ErrorChanged", "数据已被其他人修改" },
                { "Enum.Status.NotFound", "未找到记录" },
                { "Enum.Status.UserNotFound", "用户没有找到" },
                { "Enum.Status.PasswordError", "密码错误" },
                { "Enum.Status.LogonDeny", "登录被拒绝" },
                { "Enum.Status.ErrorOnline", "只允许登录一次" },
                { "Enum.Status.ErrorMacAddress", "Mac地址不正确，登录被阻止" },
                { "Enum.Status.ErrorIpAddress", "IP地址不正确，登录被阻止" },
                { "Enum.Status.ErrorOnlineLimit", "同时在线用户数量限制" },
                { "Enum.Status.PasswordCanNotBeNull", "密码不允许为空" },
                { "Enum.Status.PasswordCanNotBeRepeat", "密码不允许重复" },
                { "Enum.Status.SetPasswordOk", "设置密码成功" },
                { "Enum.Status.OldPasswordError", "原密码错误" },
                { "Enum.Status.ChangePasswordOk", "修改密码成功" },
                { "Enum.Status.UserNotEmail", "没有电子邮件地址" },
                { "Enum.Status.UserLocked", "被锁定" },
                { "Enum.Status.UserNotActive", "用户未激活" },
                { "Enum.Status.UserIsActivate", "用户已被激活，不用重复激活" },
                { "Enum.Status.ErrorLogon", "用户名或密码错误，由于安全原因不能告诉你具体哪个错误了" },
                { "Enum.Status.WaitForAudit", "待审核状态" },
                { "Enum.Status.UserDuplicate", "用户名重复" },
                { "Enum.Status.UserLogon", "用户登录" },
                { "Enum.Status.Timeout", "已经超时，请重新登录" },
                { "Enum.Status.ChangePassword", "修改密码" },
                { "Enum.Status.WeakPassword", "密码不符合规范" },
                { "Enum.Status.UserNotMobile", "没有手机号码" },
                { "Enum.Status.IpLimit", "访问被限制，过于频繁操作" },
                { "Enum.Status.LogonLimit", "登录被限制，过于频繁操作" },
                { "Enum.Status.UserNameLimit", "登录被限制，用户名过于频繁操作" },
                { "Enum.Status.PasswordLimit", "登录被限制，密码过于频繁操作" },
                { "Enum.Status.ServiceNotStart", "服务未开始" },
                { "Enum.Status.ServiceExpired", "服务到期" },
                { "Enum.Status.ParameterError", "参数错误" },
                { "Enum.Status.NotAllowEdit", "不允许修改" },
                { "Enum.Status.SignOut", "退出系统" },
                { "Enum.Status.CompanyNotFound", "公司没有找到" },
                { "Enum.Status.VerificationCodeError", "验证码错误" },
                { "Enum.Status.SignatureError", "数据被篡改，网络被劫持" },
                { "Enum.AuditStatus.Pause", "暂停" },
                { "Enum.AuditStatus.Draft", "草稿" },
                { "Enum.AuditStatus.StartAudit", "提交" },
                { "Enum.AuditStatus.AuditPass", "通过" },
                { "Enum.AuditStatus.WaitForAudit", "待审" },
                { "Enum.AuditStatus.Transmit", "转发" },
                { "Enum.AuditStatus.AuditReject", "退回" },
                { "Enum.AuditStatus.AuditComplete", "完成" },
                { "Enum.AuditStatus.AuditQuash", "废弃" },
                { "Enum.AuditStatus.AuditAccept", "受理" },

                // 异常消息与业务状态消息（异常 11 + 结果/登录 5）
                { "Exception.NoWritePermission", "当前操作系统用户没有权限写入文件 {0}" },
                { "Exception.GenericNotSupported", "不支持泛型,必须为基础实体类" },
                { "Exception.ExpressionIllegalChar", "表达式包含非法字符。" },
                { "Exception.ExpressionEmpty", "表达式不能为空。" },
                { "Exception.ExpressionSyntaxError", "表达式语法错误。" },
                { "Exception.DivideByZero", "除数不能为零。" },
                { "Exception.BracketMismatch", "括号不匹配。" },
                { "Exception.ExpressionIllegalNumber", "表达式包含非法数字。" },
                { "Exception.FileNotFound", "{0}文件不存在！" },
                { "Exception.BackupFileNotFound", "{0}文件不存在！无法备份此文件！" },
                { "Exception.InvalidIp", "无效IP" },
                { "Result.UnknownError", "未知错误" },
                { "Logon.Success", "登录成功" },
                { "Logon.AccessDeniedAdmin", "访问被拒绝、您的账户没有后台管理访问权限。" },
                { "Logon.AccessDenied", "访问被拒绝、您的账户没有访问权限。" },
                { "Logon.RequireUniqueUserName", "请用唯一用户名登录、若不知道唯一用户名、请向公司的管理员索取。" },
                // ===== 日志消息 =====
                { "Log.AddLogTaskFailedWithUser", "AddLogTask: 异常信息:{0}userName:{1}{2}错误源:{3}{2}堆栈信息:{4}" },
                { "Log.AddLogTaskFailed", "AddLogTask: 异常信息:{0}{1}错误源:{2}{1}堆栈信息:{3}" },
                { "Log.SaveEntityChangeLogTypeMismatch", "比较的实体类型不一样或非实体类型" },
                { "Log.ServiceFail", "服务调用失败，请检查：{0}" },
                { "Log.ConfigParseFailed", "UserConfigUtil 配置解析失败：{0}={1}，已使用默认值。" },
                { "Log.DisposeMemberFailed", "Dispose 释放成员对象失败: {0}" },
                { "Log.DisposeFailed", "Dispose 释放对象失败: {0}" },
                { "Log.GetSourceTextByUrlFailed", "GetSourceTextByUrl 获取URL内容失败: {0}" },
                { "Log.RestartIisFailed", "RestartIisProcess 重写 web.config 失败" },
                { "Log.RemoteSaveAsFailed", "RemoteSaveAs 下载远程文件失败: {0}" },
                { "Log.TemplateFileNotFound", "找不到模板文件" },
                { "Log.OpenTemplateFailed", "打开模板文件失败" },

                // ===== 控制台输出 =====
                { "Console.Completed", "{0} : 完成 " },
                { "Console.OcrGeneral", "通用文字识别:" },
                { "Console.ParallelTaskStart", "Parallel任务{0}开始工作……" },
                { "Console.TaskStart", "任务{0}开始工作……" },

                // ===== AppMessage.Service 功能名常量 =====
                { "Service.FileService", "档案服务" },
                { "Service.FileServiceSystemCreateDirectory", "系统创建目录" },
                { "Service.FileServiceCompanyFile", "公司文档" },
                { "Service.FileServiceShareFolder", "公共文档" },
                { "Service.FileServiceUserSpace", "用户空间" },
                { "Service.FileServiceFolder", " 的文件夾" },
                { "Service.FileServiceSendFile", "发送的文件" },
                { "Service.FileServiceFile", " 的文件" },
                { "Service.FileServiceReceiveFile", "收到的文件" },
                { "Service.FileServiceSendFileFrom", " 发送文件 " },
                { "Service.FileServiceCheckReceiveFile", "，请注意查收。" },
                { "Service.FileServiceGetEntity", "取得实体" },
                { "Service.FileServiceExists", "判断是否存在" },
                { "Service.FileServiceDownload", "下载文件" },
                { "Service.FileServiceUpload", "上传档案" },
                { "Service.FileServiceGetDataTableByFolder", "依文件夹取得档案列表" },
                { "Service.FileServiceGetDataTableByIds", "依文件ID取得档案列表" },
                { "Service.FileServiceDeleteByFolder", "依文件夹删除档案" },
                { "Service.UserService", "用户管理服务" },
                { "Service.UserServiceCheck", "请审核。" },
                { "Service.UserServiceApplication", " 申请帐户：" },
                { "Service.UserServiceAddUser", "新增用户" },
                { "Service.UserServiceGetDataTableByDepartment", "依部门取得用户列表" },
                { "Service.UserServiceGetEntity", "取得实体" },
                { "Service.UserServiceGetDataTable", "取得列表" },
                { "Service.UserServiceGetDataTableByRole", "依角色取得列表" },
                { "Service.UserServiceGetDataTableByIds", "依主键取得列表" },
                { "Service.UserServiceGetRoleDataTable", "取得用户的角色列表" },
                { "Service.UserServiceUserInRole", "判断用户是否在某个角色中" },
                { "Service.UserServiceUpdateUser", "更新用户" },
                { "Service.UserServiceSearch", "查询用户" },
                { "Service.UserServiceSetUserAuditStates", "设置用户审核状态" },
                { "Service.UserServiceSetDefaultRole", "设置用户的预设角色" },

                // ===== 补漏：登录状态消息（P5）=====
                { "Logon.UserNotFound", "未找到对应的用户" },
                { "Logon.PasswordResetMailSent", "新密码已发送到您的注册邮箱{0}，请注意查收。" },
                { "Logon.UpdateDatabaseFailed", "更新数据库失败，请重试！" },
                { "Logon.UserLockedCannotResetPassword", "用户被锁定，不允许重置密码。" },
                { "Logon.UserNotFoundRetry", "用户未找到，请重新输入用户名。" },
                { "Logon.UserLockedCannotSetPassword", "用户被锁定，不允许设置密码。" },
                { "Logon.UserNotActivated", "用户还未被激活，不允许设置密码。" },
                { "Logon.AppUserNotFound", "应用系统用户不存在，请联系管理员。" },
                { "Logon.DomainServerResponse", "域服务器返回信息{0}" },
                { "Logon.Failed", "登录失败" },

                // ===== 补漏：业务操作错误消息（P5）=====
                { "Business.DataAlreadyDeleted", "数据已被删除，无需再次删除" },
                { "Business.DataNotDeleted", "数据未被删除，无需撤销" },
                { "Business.DataAlreadyEnabled", "数据已启用，无需再次启用" },
                { "Business.DataAlreadyDisabled", "数据已禁用，无需再次禁用" },
                { "Business.SystemDataNoPermission", "系统数据无权操作" },
                { "Business.OtherCompanyDataNoPermission", "非本公司数据无权操作" },

                // ===== 补漏：工具类返回消息（P5）=====
                { "Rmb.Overflow", "溢出" },
                { "Rmb.NotNumeric", "非数字形式！" },
                { "Qqwry.Unknown", "未知" },
                { "Sms.InvalidMobile", "手机号码有误！" }
            };
        }
    }
}