//-----------------------------------------------------------------
// All Rights Reserved. Copyright (c) 2026, DotNet.
//-----------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DotNet.Util
{
    /// <summary>
    /// 英文语言包，第一个语言包，其它语言缺键时回退到中文包。
    /// 键集合必须与中文包 MsgPack.zh-CN.cs 完全一致，由单元测试 MsgTests 断言校验。
    /// 词条与 AppMessage.MsgXXXX 字段一一对应（共 240 条）。
    /// </summary>
    public static partial class MsgPack
    {
        private static Dictionary<string, string> EnMessages()
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Common.ParameterRequired", "Please enter {0}; it cannot be empty." },
                { "Common.Success", "The operation succeeded." },
                { "Common.UnknownError", "An unknown error occurred." },
                { "Msg0000", "Information" },
                { "Msg0001", "An unknown error occurred." },
                { "Msg0002", "The database connection is not working." },
                { "Msg0003", "The web service connection is not working." },
                { "Msg0004", "No data was modified." },
                { "Msg0005", "The record was not found. Check your network connection; it may also have been deleted by another user. Contact the system administrator to verify." },
                { "Msg0006", "The data has been modified by another user. Press F5 to retrieve the latest data." },
                { "Msg0007", "Please enter {0}; it cannot be empty." },
                { "Msg0008", "{0} already exists." },
                { "Msg0009", "Added successfully." },
                { "Msg0010", "Updated successfully." },
                { "Msg0011", "Saved successfully." },
                { "Msg0012", "Batch saved successfully." },
                { "Msg0013", "Deleted successfully." },
                { "Msg0014", "Batch deleted successfully." },
                { "Msg0015", "Are you sure you want to delete it?" },
                { "Msg0016", "Are you sure you want to delete {0}?" },
                { "Msg0017", "The current record cannot be deleted." },
                { "Msg0018", "The current record {0} cannot be deleted." },
                { "Msg0019", "The current record cannot be edited. Press F5 to retrieve the latest data." },
                { "Msg0020", "The current record {0} cannot be edited. Press F5 to retrieve the latest data." },
                { "Msg0021", "This is already the first record." },
                { "Msg0022", "This is already the last record." },
                { "Msg0024", "Please select at least one {0}." },
                { "Msg0025", "{0} cannot be greater than {1}." },
                { "Msg0026", "{0} cannot be less than {1}." },
                { "Msg0027", "{0} cannot be equal to {1}." },
                { "Msg0028", "{0} is not a valid date." },
                { "Msg0029", "{0} is not a valid character." },
                { "Msg0030", "{0} is not a valid number." },
                { "Msg0031", "{0} is not a valid amount." },
                { "Msg0032", "The {0} name contains invalid characters." },
                { "Msg0033", "The data is already referenced by related records." },
                { "Msg0034", "The data is already referenced by related records. Force delete it anyway?" },
                { "Msg0035", "{0} has child nodes that have not been deleted, so it cannot be deleted." },
                { "Msg0036", "{0} cannot be moved to {1}." },
                { "Msg0037", "The child nodes under {0} cannot be moved to {1}." },
                { "Msg0038", "Are you sure you want to move {0} to {1}?" },
                { "Msg0039", "{0} is not equal to {1}." },
                { "Msg0040", "{0} error." },
                { "Msg0041", "Are you sure you want to approve it?" },
                { "Msg0042", "Are you sure you want to return it?" },
                { "Msg0043", "The data cannot be locked." },
                { "Msg0044", "The data was locked successfully." },
                { "Msg0045", "The data has changed. Save the changes?" },
                { "Msg0046", "The password cannot be repeated within the last {0} changes." },
                { "Msg0047", "The password has expired and the account is locked. Contact the system administrator." },
                { "Msg0048", "Sign-in denied: the user is already online." },
                { "Msg0049", "Sign-in denied: the network adapter MAC address does not meet the restriction." },
                { "Msg0050", "Sign-in denied: the IP address {0} is restricted. Contact the system administrator." },
                { "Msg0051", "The maximum number of online users has been reached." },
                { "Msg0052", "The IP address format is incorrect." },
                { "Msg0053", "The MAC address format is incorrect." },
                { "Msg0054", "Please enter an IP address or a MAC address." },
                { "Msg0055", "A duplicate IP address already exists." },
                { "Msg0056", "The IP address was added successfully." },
                { "Msg0057", "Failed to add the IP address." },
                { "Msg0058", "A duplicate MAC address already exists." },
                { "Msg0059", "The MAC address was added successfully." },
                { "Msg0060", "Please create the sign-in account for this staff member first." },
                { "Msg0061", "Failed to add the MAC address." },
                { "Msg0062", "Please set a new password; the original password has never been changed." },
                { "Msg0063", "Please set a new password; it has not been changed for 30 days." },
                { "Msg0064", "The minute value you entered is incorrect. Please check it." },
                { "Msg0065", "The data has changed. Discard the changes?" },
                { "Msg0066", "Please set a new password; the system requires a password change." },
                { "Msg0075", "Are you sure you want to remove it?" },
                { "Msg0076", "Are you sure you want to remove {0}?" },
                { "Msg0077", "{0} record(s) deleted successfully." },
                { "Msg0078", "Sign-in denied: the user is pending approval." },
                { "Msg0079", "The user is locked and sign-in was denied. Try again in 1 minute or contact the system administrator." },
                { "Msg0080", "The user account is not activated. Please activate it." },
                { "Msg0081", "The user is locked and sign-in was denied. Not before:" },
                { "Msg0082", "The user is locked and sign-in was denied. Not after:" },
                { "Msg0083", "The user is locked and sign-in was denied. Lock start date:" },
                { "Msg0084", "The user is locked and sign-in was denied. Lock end date:" },
                { "Msg0085", "The IP address is incorrect." },
                { "Msg0086", "The MAC address is incorrect." },
                { "Msg0087", "The user is already online; repeated sign-in is not allowed." },
                { "Msg0088", "Incorrect password; sign-in was denied." },
                { "Msg0089", "The online user limit has been exceeded:" },
                { "Msg0090", "Sign-in was denied." },
                { "Msg0091", "Add an operation permission item." },
                { "Msg0092", "Sign-in start time" },
                { "Msg0093", "Sign-in end time" },
                { "Msg0094", "Suspend start time" },
                { "Msg0095", "Suspend end date" },
                { "Msg0100", "{0} is online and cannot be deleted." },
                { "Msg0101", "The current user {0} cannot delete themselves." },
                { "Msg0102", "Consecutive duplicate passwords are not allowed." },
                { "Msg0200", "Are you sure you want to clear the user role associations?" },
                { "Msg0201", "The file you selected does not exist. Please select again." },
                { "Msg0202", "Information" },
                { "Msg0203", "Are you sure you want to move \"{0}\" to \"{1}\"?" },
                { "Msg0204", "Are you sure you want to exit the application?" },
                { "Msg0205", "The file {0} already exists. Overwrite the file on the server?" },
                { "Msg0206", "The upload limit has been exceeded. Please check the file size." },
                { "Msg0207", "Are you sure you want to delete the image?" },
                { "Msg0208", "The start time cannot be later than the end time." },
                { "Msg0209", "Cleared successfully." },
                { "Msg0210", "Reset successfully." },
                { "Msg0211", "An incorrect password has been entered {0} times. Further sign-in is not allowed. Please restart the application and sign in again." },
                { "Msg0212", "Query content" },
                { "Msg0213", "The total length of the code must not exceed 40 characters." },
                { "Msg0214", "The code was generated successfully." },
                { "Msg0215", "Ascending sequence" },
                { "Msg0216", "Descending sequence" },
                { "Msg0217", "Step" },
                { "Msg0218", "The sequence was reset successfully." },
                { "Msg0219", "Are you sure you want to reset the sequence?" },
                { "Msg0223", "The user name cannot be empty. Please enter it." },
                { "Msg0225", "The current node still has data." },
                { "Msg0226", "You cannot delete yourself." },
                { "Msg0228", "The related user was set successfully." },
                { "Msg0229", "The company cannot be empty. Please select one." },
                { "Msg0230", "The account request was updated successfully. Please wait for approval." },
                { "Msg0231", "The password does not match the confirmation password. Please re-enter." },
                { "Msg0232", "User name" },
                { "Msg0233", "Full name" },
                { "Msg0234", "The email format is incorrect. Please re-enter." },
                { "Msg0235", "The account was requested successfully. Please wait for approval." },
                { "Msg0236", "The export target file already exists. Overwrite \"{0}\"?" },
                { "Msg0237", "The email was sent successfully." },
                { "Msg0238", "The exception information was cleared successfully." },
                { "Msg0239", "Are you sure you want to clear the exception information?" },
                { "Msg0240", "Content cannot be empty" },
                { "Msg0241", "Failed to send the email." },
                { "Msg0242", "Moved successfully." },
                { "Msg0243", "Application exception report" },
                { "Msg0244", "The document you selected does not exist. Please select again." },
                { "Msg0246", "No data to copy!" },
                { "Msg0274", "Please select the data to process." },
                { "Msg0275", "Are you sure you want to submit without a return reason?" },
                { "Msg0276", "Are you sure you want to revoke this document in the approval workflow?" },
                { "Msg0277", "Please select the user to submit for approval." },
                { "Msg0278", "Are you sure you want to submit to user {0} for approval?" },
                { "Msg0279", "The workflow was sent successfully." },
                { "Msg0280", "Failed to send the workflow." },
                { "Msg0281", "Are you sure you want to replace the file {0}?" },
                { "Msg0282", "Parent organization" },
                { "Msg0283", "The code was generated successfully" },
                { "Msg0284", "The configuration has been modified. Save the changes?" },
                { "Msg0285", "No data to save!" },
                { "Msg0286", "Company name" },
                { "Msg0287", "Please select the department to submit for approval." },
                { "Msg0288", "Are you sure you want to submit to department {0} for approval?" },
                { "Msg0289", "Please select the role to submit for approval." },
                { "Msg0290", "Are you sure you want to submit to role {0} for approval?" },
                { "Msg0291", "Please select the role, department, or user to submit for approval." },
                { "Msg0292", "{0} item(s) returned successfully." },
                { "Msg0293", "Failed to return." },
                { "Msg0294", "Are you sure you want to forward to {0} for approval?" },
                { "Msg0295", "{0} item(s) forwarded successfully." },
                { "Msg0296", "Failed to forward." },
                { "Msg0300", "Sign-off notice: your account signed in from another location, so you have been signed out." },
                { "Msg0301", "Are you sure you want to save?" },
                { "Msg0302", "Category." },
                { "Msg0303", "Please select {0}." },
                { "Msg0304", "You must select one of user, organization, or role." },
                { "Msg0400", "Your account sign-in is abnormal and has been locked by the system for {0} minutes. Contact the system administrator if you have questions." },
                { "Msg0600", "Are you sure you want to clear the permissions?" },
                { "Msg0700", "Successfully connected to the target data source." },
                { "Msg0750", "Debug information" },
                { "Msg0800", "Access denied: unauthorized access." },
                { "Msg0900", "Service call denied: the user is not signed in." },
                { "Msg1000", "System configuration message error. Please contact the software vendor." },
                { "Msg1001", "Are you sure you want to reset the function menu?" },
                { "Msg2000", "{0} is incorrect. Please re-enter." },
                { "Msg3000", "Are you sure you want to initialize the system?" },
                { "Msg3010", "The operation succeeded." },
                { "Msg3020", "The operation failed." },
                { "Msg8000", "The password does not meet the strength requirements. It must be at least 8 characters and combine letters and digits." },
                { "Msg8700", "Mobile phone" },
                { "Msg8800", "Email" },
                { "Msg8900", "Employee number" },
                { "Msg9000", "Incorrect user name or password" },
                { "Msg9660", "Service not started" },
                { "Msg9665", "Service expired" },
                { "Msg9800", "Value" },
                { "Msg9900", "Company" },
                { "Msg9901", "Department" },
                { "Msg9910", "The user has no email address configured." },
                { "Msg9911", "The user account is locked. Try again in 1 minute or contact the system administrator." },
                { "Msg9912", "The user has not activated the account." },
                { "Msg9913", "The user account has been activated." },
                { "Msg9914", "User association." },
                { "Msg9915", "Please set the constraint conditions." },
                { "Msg9916", "Show   ▽" },
                { "Msg9917", "Hide   △" },
                { "Msg9918", "The expression was validated successfully." },
                { "Msg9919", "Please enter the condition." },
                { "Msg9920", "Please enter the content." },
                { "Msg9921", "Missing the ( symbol." },
                { "Msg9922", "Missing the ) symbol." },
                { "Msg9954", "Unique user name" },
                { "Msg9955", "Data" },
                { "Msg9956", "No records found matching the criteria" },
                { "Msg9957", "User name" },
                { "Msg9958", "Data validation error" },
                { "Msg9959", "New password" },
                { "Msg9960", "Confirm password" },
                { "Msg9961", "Current password" },
                { "Msg9962", "{0} changed successfully." },
                { "Msg9963", "{0} set successfully." },
                { "Msg9964", "Password" },
                { "Msg9965", "Executed successfully." },
                { "Msg9966", "User not found. Please check the letter case." },
                { "Msg9967", "Incorrect password. Please check the letter case." },
                { "Msg9968", "Sign-in denied: the account is disabled. Please contact the system administrator." },
                { "Msg9969", "Base code" },
                { "Msg9970", "Staff" },
                { "Msg9971", "Organization" },
                { "Msg9972", "Role" },
                { "Msg9973", "Menu" },
                { "Msg9974", "Folder" },
                { "Msg9975", "Permission" },
                { "Msg9976", "Primary key" },
                { "Msg9977", "Code" },
                { "Msg9978", "Name" },
                { "Msg9979", "Parent id" },
                { "Msg9980", "Parent name" },
                { "Msg9981", "Category id" },
                { "Msg9982", "Unique id" },
                { "Msg9983", "Subject" },
                { "Msg9984", "Content" },
                { "Msg9985", "Status code" },
                { "Msg9986", "Count" },
                { "Msg9987", "Enabled" },
                { "Msg9988", "Remark" },
                { "Msg9989", "Sort code" },
                { "Msg9990", "Created by" },
                { "Msg9991", "Created on" },
                { "Msg9992", "Modified by" },
                { "Msg9993", "Modified on" },
                { "Msg9994", "Sort" },
                { "Msg9995", "Primary key" },
                { "Msg9996", "Index" },
                { "Msg9997", "Field" },
                { "Msg9998", "Table" },
                { "Msg9999", "Database" },
                { "MsgReLogon", "Sign in again" },
                { "Msgc023", "Please select at least one item." },
                { "Msgc024", "Only one record can be selected." },
                { "Msgs857", "Signature private key." },
                { "Msgs864", "Signature password." },
                { "Msgs957", "Communication user name." },
                { "Msgs964", "Communication password." },
                { "Msgs965", "Verification code" },

                // 枚举描述（键格式 Enum.<类型>.<成员>，与 Status.cs / AuditStatus.cs 一一对应）
                { "Enum.Status.SystemCodeError", "Invalid system code; sign-in blocked" },
                { "Enum.Status.AccessDeny", "Unauthorized access; access blocked" },
                { "Enum.Status.DbError", "Database connection error" },
                { "Enum.Status.UserOnline", "User is already online" },
                { "Enum.Status.UserNotLogin", "User is not signed in" },
                { "Enum.Status.MissingData", "Missing user sign-in data" },
                { "Enum.Status.Error", "An error occurred" },
                { "Enum.Status.Ok", "Operation succeeded" },
                { "Enum.Status.OkAdd", "Added successfully" },
                { "Enum.Status.CanNotLock", "Unable to lock the data" },
                { "Enum.Status.LockOk", "Data locked successfully" },
                { "Enum.Status.OkUpdate", "Updated successfully" },
                { "Enum.Status.OkDelete", "Deleted successfully" },
                { "Enum.Status.Exist", "The data already exists; duplicates are not allowed" },
                { "Enum.Status.ErrorCodeExist", "The code already exists; duplicates are not allowed" },
                { "Enum.Status.ErrorNameExist", "The name already exists" },
                { "Enum.Status.ErrorValueExist", "The value already exists" },
                { "Enum.Status.ErrorUserExist", "The user name already exists" },
                { "Enum.Status.OkOperation", "Completed successfully" },
                { "Enum.Status.ErrorDataRelated", "The data is referenced by related records" },
                { "Enum.Status.ErrorDeleted", "The data has been deleted by someone else" },
                { "Enum.Status.ErrorUpdate", "Failed to update the data" },
                { "Enum.Status.ErrorChanged", "The data has been modified by someone else" },
                { "Enum.Status.NotFound", "Record not found" },
                { "Enum.Status.UserNotFound", "User not found" },
                { "Enum.Status.PasswordError", "Incorrect password" },
                { "Enum.Status.LogonDeny", "Sign-in denied" },
                { "Enum.Status.ErrorOnline", "Only one concurrent sign-in is allowed" },
                { "Enum.Status.ErrorMacAddress", "Invalid MAC address; sign-in blocked" },
                { "Enum.Status.ErrorIpAddress", "Invalid IP address; sign-in blocked" },
                { "Enum.Status.ErrorOnlineLimit", "Concurrent user limit reached" },
                { "Enum.Status.PasswordCanNotBeNull", "Password cannot be empty" },
                { "Enum.Status.PasswordCanNotBeRepeat", "Password cannot be reused" },
                { "Enum.Status.SetPasswordOk", "Password set successfully" },
                { "Enum.Status.OldPasswordError", "Current password is incorrect" },
                { "Enum.Status.ChangePasswordOk", "Password changed successfully" },
                { "Enum.Status.UserNotEmail", "No email address" },
                { "Enum.Status.UserLocked", "Locked" },
                { "Enum.Status.UserNotActive", "User is not activated" },
                { "Enum.Status.UserIsActivate", "User is already activated" },
                { "Enum.Status.ErrorLogon", "Incorrect user name or password; for security reasons the exact reason is not disclosed" },
                { "Enum.Status.WaitForAudit", "Pending review" },
                { "Enum.Status.UserDuplicate", "Duplicate user name" },
                { "Enum.Status.UserLogon", "User sign-in" },
                { "Enum.Status.Timeout", "Session timed out; please sign in again" },
                { "Enum.Status.ChangePassword", "Change password" },
                { "Enum.Status.WeakPassword", "Password does not meet the policy" },
                { "Enum.Status.UserNotMobile", "No mobile number" },
                { "Enum.Status.IpLimit", "Access restricted due to frequent operations" },
                { "Enum.Status.LogonLimit", "Sign-in restricted due to frequent attempts" },
                { "Enum.Status.UserNameLimit", "Sign-in restricted: user name tried too frequently" },
                { "Enum.Status.PasswordLimit", "Sign-in restricted: password tried too frequently" },
                { "Enum.Status.ServiceNotStart", "Service has not started" },
                { "Enum.Status.ServiceExpired", "Service expired" },
                { "Enum.Status.ParameterError", "Parameter error" },
                { "Enum.Status.NotAllowEdit", "Editing is not allowed" },
                { "Enum.Status.SignOut", "Signed out" },
                { "Enum.Status.CompanyNotFound", "Company not found" },
                { "Enum.Status.VerificationCodeError", "Incorrect verification code" },
                { "Enum.Status.SignatureError", "Data tampered with; network hijacked" },
                { "Enum.AuditStatus.Pause", "Paused" },
                { "Enum.AuditStatus.Draft", "Draft" },
                { "Enum.AuditStatus.StartAudit", "Submitted" },
                { "Enum.AuditStatus.AuditPass", "Approved" },
                { "Enum.AuditStatus.WaitForAudit", "Pending" },
                { "Enum.AuditStatus.Transmit", "Forwarded" },
                { "Enum.AuditStatus.AuditReject", "Rejected" },
                { "Enum.AuditStatus.AuditComplete", "Completed" },
                { "Enum.AuditStatus.AuditQuash", "Discarded" },
                { "Enum.AuditStatus.AuditAccept", "Accepted" },

                // 异常消息与业务状态消息（异常 11 + 结果/登录 5）
                { "Exception.NoWritePermission", "The current OS user has no permission to write file {0}" },
                { "Exception.GenericNotSupported", "Generic types are not supported; a concrete entity class is required" },
                { "Exception.ExpressionIllegalChar", "The expression contains illegal characters." },
                { "Exception.ExpressionEmpty", "The expression cannot be empty." },
                { "Exception.ExpressionSyntaxError", "Expression syntax error." },
                { "Exception.DivideByZero", "The divisor cannot be zero." },
                { "Exception.BracketMismatch", "Brackets do not match." },
                { "Exception.ExpressionIllegalNumber", "The expression contains an illegal number." },
                { "Exception.FileNotFound", "File {0} does not exist!" },
                { "Exception.BackupFileNotFound", "File {0} does not exist! Unable to back up this file!" },
                { "Exception.InvalidIp", "Invalid IP" },
                { "Result.UnknownError", "Unknown error" },
                { "Logon.Success", "Sign-in succeeded" },
                { "Logon.AccessDeniedAdmin", "Access denied: your account has no back-office administration permission." },
                { "Logon.AccessDenied", "Access denied: your account has no access permission." },
                { "Logon.RequireUniqueUserName", "Please sign in with a unique user name; if you do not know it, ask your company administrator." },

                // ===== 日志消息 =====
                { "Log.AddLogTaskFailedWithUser", "AddLogTask: Exception: {0}userName:{1}{2}Source: {3}{2}Stack trace: {4}" },
                { "Log.AddLogTaskFailed", "AddLogTask: Exception: {0}{1}Source: {2}{1}Stack trace: {3}" },
                { "Log.SaveEntityChangeLogTypeMismatch", "The compared entity types differ, or the type is not an entity type" },
                { "Log.ServiceFail", "Service invocation failed, please check: {0}" },
                { "Log.ConfigParseFailed", "UserConfigUtil failed to parse configuration: {0}={1}. The default value is used." },
                { "Log.DisposeMemberFailed", "Dispose failed to release the member object: {0}" },
                { "Log.DisposeFailed", "Dispose failed to release the object: {0}" },
                { "Log.GetSourceTextByUrlFailed", "GetSourceTextByUrl failed to retrieve URL content: {0}" },
                { "Log.RestartIisFailed", "RestartIisProcess failed to rewrite web.config" },
                { "Log.RemoteSaveAsFailed", "RemoteSaveAs failed to download the remote file: {0}" },
                { "Log.TemplateFileNotFound", "Template file not found" },
                { "Log.OpenTemplateFailed", "Failed to open the template file" },

                // ===== 控制台输出 =====
                { "Console.Completed", "{0} : done " },
                { "Console.OcrGeneral", "General text recognition:" },
                { "Console.ParallelTaskStart", "Parallel task {0} starting..." },
                { "Console.TaskStart", "Task {0} starting..." },

                // ===== AppMessage.Service 功能名常量 =====
                { "Service.FileService", "Archive service" },
                { "Service.FileServiceSystemCreateDirectory", "System created directory" },
                { "Service.FileServiceCompanyFile", "Company documents" },
                { "Service.FileServiceShareFolder", "Shared documents" },
                { "Service.FileServiceUserSpace", "User space" },
                { "Service.FileServiceFolder", "'s folder" },
                { "Service.FileServiceSendFile", "Sent files" },
                { "Service.FileServiceFile", "'s files" },
                { "Service.FileServiceReceiveFile", "Received files" },
                { "Service.FileServiceSendFileFrom", " sent file " },
                { "Service.FileServiceCheckReceiveFile", ", please check and acknowledge." },
                { "Service.FileServiceGetEntity", "Get entity" },
                { "Service.FileServiceExists", "Check existence" },
                { "Service.FileServiceDownload", "Download file" },
                { "Service.FileServiceUpload", "Upload archive" },
                { "Service.FileServiceGetDataTableByFolder", "Get archive list by folder" },
                { "Service.FileServiceGetDataTableByIds", "Get archive list by file ID" },
                { "Service.FileServiceDeleteByFolder", "Delete archives by folder" },
                { "Service.UserService", "User management service" },
                { "Service.UserServiceCheck", "Please review." },
                { "Service.UserServiceApplication", " applied for an account: " },
                { "Service.UserServiceAddUser", "Add user" },
                { "Service.UserServiceGetDataTableByDepartment", "Get user list by department" },
                { "Service.UserServiceGetEntity", "Get entity" },
                { "Service.UserServiceGetDataTable", "Get list" },
                { "Service.UserServiceGetDataTableByRole", "Get list by role" },
                { "Service.UserServiceGetDataTableByIds", "Get list by ID" },
                { "Service.UserServiceGetRoleDataTable", "Get the role list of the user" },
                { "Service.UserServiceUserInRole", "Check whether the user is in a role" },
                { "Service.UserServiceUpdateUser", "Update user" },
                { "Service.UserServiceSearch", "Search users" },
                { "Service.UserServiceSetUserAuditStates", "Set user audit status" },
                { "Service.UserServiceSetDefaultRole", "Set the default role of the user" },

                // ===== 补漏：登录状态消息（P5）=====
                { "Logon.UserNotFound", "The corresponding user was not found" },
                { "Logon.PasswordResetMailSent", "The new password has been sent to your registered mailbox {0}, please check it." },
                { "Logon.UpdateDatabaseFailed", "Failed to update the database, please retry!" },
                { "Logon.UserLockedCannotResetPassword", "The user is locked; resetting the password is not allowed." },
                { "Logon.UserNotFoundRetry", "User not found, please re-enter the user name." },
                { "Logon.UserLockedCannotSetPassword", "The user is locked; setting a password is not allowed." },
                { "Logon.UserNotActivated", "The user is not activated yet; setting a password is not allowed." },
                { "Logon.AppUserNotFound", "The application system user does not exist, please contact the administrator." },
                { "Logon.DomainServerResponse", "Domain server returned: {0}" },
                { "Logon.Failed", "Sign-in failed" },

                // ===== 补漏：业务操作错误消息（P5）=====
                { "Business.DataAlreadyDeleted", "The data has already been deleted; there is no need to delete it again" },
                { "Business.DataNotDeleted", "The data has not been deleted; there is no need to undo" },
                { "Business.DataAlreadyEnabled", "The data is already enabled; there is no need to enable it again" },
                { "Business.DataAlreadyDisabled", "The data is already disabled; there is no need to disable it again" },
                { "Business.SystemDataNoPermission", "No permission to operate on system data" },
                { "Business.OtherCompanyDataNoPermission", "No permission to operate on data of another company" },

                // ===== 补漏：工具类返回消息（P5）=====
                { "Rmb.Overflow", "Overflow" },
                { "Rmb.NotNumeric", "Not a numeric value!" },
                { "Qqwry.Unknown", "Unknown" },
                { "Sms.InvalidMobile", "Invalid mobile number!" }
            };
        }
    }
}
