//-----------------------------------------------------------------
// All Rights Reserved. Copyright (c) 2026, DotNet.
//-----------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DotNet.Util
{
    /// <summary>
    /// 英文语言包，第一个语言包，其它语言缺键时回退到中文包。
    /// 键集合必须与中文包 MsgPack.zh-CN.cs 完全一致，由单元测试 MsgTests 断言校验。
    /// 词条与 AppMessage.MsgXXXX 字段一一对应（共 240 条）。
    /// </summary>
    public static partial class MsgPack
    {
        private static Dictionary<string, string> EnMessages()
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Common.ParameterRequired", "Please enter {0}; it cannot be empty." },
                { "Common.Success", "The operation succeeded." },
                { "Common.UnknownError", "An unknown error occurred." },
                { "Common.Prompt", "Information" },
                { "System.DbConnectionFailed", "The database connection is not working." },
                { "System.WebServiceConnectionFailed", "The web service connection is not working." },
                { "Common.NoDataModified", "No data was modified." },
                { "Common.RecordNotFound", "The record was not found. Check your network connection; it may also have been deleted by another user. Contact the system administrator to verify." },
                { "Common.DataChangedByOthers", "The data has been modified by another user. Press F5 to retrieve the latest data." },
                { "Validation.Duplicated", "{0} already exists." },
                { "Result.AddSuccess", "Added successfully." },
                { "Result.UpdateSuccess", "Updated successfully." },
                { "Result.SaveSuccess", "Saved successfully." },
                { "Result.BatchSaveSuccess", "Batch saved successfully." },
                { "Result.DeleteSuccess", "Deleted successfully." },
                { "Result.BatchDeleteSuccess", "Batch deleted successfully." },
                { "Confirm.Delete", "Are you sure you want to delete it?" },
                { "Confirm.DeleteItem", "Are you sure you want to delete {0}?" },
                { "Common.RecordDeleteNotAllowed", "The current record cannot be deleted." },
                { "Common.RecordItemDeleteNotAllowed", "The current record {0} cannot be deleted." },
                { "Common.RecordEditNotAllowed", "The current record cannot be edited. Press F5 to retrieve the latest data." },
                { "Common.RecordItemEditNotAllowed", "The current record {0} cannot be edited. Press F5 to retrieve the latest data." },
                { "Common.IsFirstRecord", "This is already the first record." },
                { "Common.IsLastRecord", "This is already the last record." },
                { "Validation.SelectAtLeastOne", "Please select at least one {0}." },
                { "Validation.NotGreaterThan", "{0} cannot be greater than {1}." },
                { "Validation.NotLessThan", "{0} cannot be less than {1}." },
                { "Validation.CanNotEqual", "{0} cannot be equal to {1}." },
                { "Validation.InvalidDate", "{0} is not a valid date." },
                { "Validation.InvalidChar", "{0} is not a valid character." },
                { "Validation.InvalidNumber", "{0} is not a valid number." },
                { "Validation.InvalidAmount", "{0} is not a valid amount." },
                { "Validation.ContainsIllegalChar", "The {0} name contains invalid characters." },
                { "Common.DataReferenced", "The data is already referenced by related records." },
                { "Confirm.ForceDeleteReferenced", "The data is already referenced by related records. Force delete it anyway?" },
                { "Common.ChildNodeExists", "{0} has child nodes that have not been deleted, so it cannot be deleted." },
                { "Common.MoveNotAllowed", "{0} cannot be moved to {1}." },
                { "Common.ChildNodeMoveNotAllowed", "The child nodes under {0} cannot be moved to {1}." },
                { "Confirm.Move", "Are you sure you want to move {0} to {1}?" },
                { "Validation.NotEqual", "{0} is not equal to {1}." },
                { "Common.ItemError", "{0} error." },
                { "Confirm.AuditPass", "Are you sure you want to approve it?" },
                { "Confirm.AuditReject", "Are you sure you want to return it?" },
                { "Common.LockFailed", "The data cannot be locked." },
                { "Common.LockSuccess", "The data was locked successfully." },
                { "Confirm.SaveChangedData", "The data has changed. Save the changes?" },
                { "Logon.PasswordCanNotRepeatInRecentTimes", "The password cannot be repeated within the last {0} changes." },
                { "Logon.PasswordExpiredAccountLocked", "The password has expired and the account is locked. Contact the system administrator." },
                { "Logon.UserAlreadyOnline", "Sign-in denied: the user is already online." },
                { "Logon.MacAddressNotAllowed", "Sign-in denied: the network adapter MAC address does not meet the restriction." },
                { "Logon.IpAddressRestricted", "Sign-in denied: the IP address {0} is restricted. Contact the system administrator." },
                { "Logon.MaxOnlineUsersReached", "The maximum number of online users has been reached." },
                { "Ip.InvalidIpFormat", "The IP address format is incorrect." },
                { "Ip.InvalidMacFormat", "The MAC address format is incorrect." },
                { "Ip.IpOrMacRequired", "Please enter an IP address or a MAC address." },
                { "Ip.DuplicateIpAddress", "A duplicate IP address already exists." },
                { "Ip.AddSuccess", "The IP address was added successfully." },
                { "Ip.AddFailed", "Failed to add the IP address." },
                { "Ip.DuplicateMacAddress", "A duplicate MAC address already exists." },
                { "Ip.MacAddSuccess", "The MAC address was added successfully." },
                { "Logon.CreateLoginAccountFirst", "Please create the sign-in account for this staff member first." },
                { "Ip.MacAddFailed", "Failed to add the MAC address." },
                { "Logon.PasswordNeverChanged", "Please set a new password; the original password has never been changed." },
                { "Logon.PasswordNotChangedIn30Days", "Please set a new password; it has not been changed for 30 days." },
                { "Validation.InvalidMinutes", "The minute value you entered is incorrect. Please check it." },
                { "Confirm.DiscardChangedData", "The data has changed. Discard the changes?" },
                { "Logon.PasswordChangeRequired", "Please set a new password; the system requires a password change." },
                { "Confirm.Remove", "Are you sure you want to remove it?" },
                { "Confirm.RemoveItem", "Are you sure you want to remove {0}?" },
                { "Result.DeleteRecordsSuccess", "{0} record(s) deleted successfully." },
                { "Logon.UserAwaitingAudit", "Sign-in denied: the user is pending approval." },
                { "Logon.UserLockedRetryAfterOneMinute", "The user is locked and sign-in was denied. Try again in 1 minute or contact the system administrator." },
                { "Logon.AccountNotActivatedPrompt", "The user account is not activated. Please activate it." },
                { "Logon.LockedNotBefore", "The user is locked and sign-in was denied. Not before:" },
                { "Logon.LockedNotAfter", "The user is locked and sign-in was denied. Not after:" },
                { "Logon.LockedStartDate", "The user is locked and sign-in was denied. Lock start date:" },
                { "Logon.LockedEndDate", "The user is locked and sign-in was denied. Lock end date:" },
                { "Ip.IpAddressIncorrect", "The IP address is incorrect." },
                { "Ip.MacAddressIncorrect", "The MAC address is incorrect." },
                { "Logon.DuplicateLoginNotAllowed", "The user is already online; repeated sign-in is not allowed." },
                { "Logon.PasswordIncorrect", "Incorrect password; sign-in was denied." },
                { "Logon.OnlineUserLimitExceeded", "The online user limit has been exceeded:" },
                { "Logon.LoginDenied", "Sign-in was denied." },
                { "Common.AddPermissionItem", "Add an operation permission item." },
                { "Logon.StartTime", "Sign-in start time" },
                { "Logon.EndTime", "Sign-in end time" },
                { "Logon.PauseStartTime", "Suspend start time" },
                { "Logon.PauseEndDate", "Suspend end date" },
                { "Logon.UserOnlineDeleteNotAllowed", "{0} is online and cannot be deleted." },
                { "Logon.DeleteSelfNotAllowed", "The current user {0} cannot delete themselves." },
                { "Logon.PasswordSequentialNotAllowed", "Consecutive duplicate passwords are not allowed." },
                { "Confirm.ClearUserRole", "Are you sure you want to clear the user role associations?" },
                { "File.SelectedFileNotExists", "The file you selected does not exist. Please select again." },
                { "Confirm.MoveQuoted", "Are you sure you want to move \"{0}\" to \"{1}\"?" },
                { "Confirm.ExitApplication", "Are you sure you want to exit the application?" },
                { "Confirm.OverwriteFile", "The file {0} already exists. Overwrite the file on the server?" },
                { "File.UploadSizeExceeded", "The upload limit has been exceeded. Please check the file size." },
                { "Confirm.DeleteImage", "Are you sure you want to delete the image?" },
                { "Validation.StartTimeAfterEndTime", "The start time cannot be later than the end time." },
                { "Result.ClearSuccess", "Cleared successfully." },
                { "Result.ResetSuccess", "Reset successfully." },
                { "Logon.TooManyPasswordAttempts", "An incorrect password has been entered {0} times. Further sign-in is not allowed. Please restart the application and sign in again." },
                { "Common.QueryContent", "Query content" },
                { "Validation.CodeTooLong", "The total length of the code must not exceed 40 characters." },
                { "Sequence.GenerateSuccess", "The code was generated successfully." },
                { "Sequence.Increment", "Ascending sequence" },
                { "Sequence.Decrement", "Descending sequence" },
                { "Sequence.Step", "Step" },
                { "Sequence.ResetSuccess", "The sequence was reset successfully." },
                { "Confirm.ResetSequence", "Are you sure you want to reset the sequence?" },
                { "Validation.UserNameRequired", "The user name cannot be empty. Please enter it." },
                { "Common.NodeHasData", "The current node still has data." },
                { "Common.DeleteSelfNotAllowed", "You cannot delete yourself." },
                { "Result.SetRelatedUserSuccess", "The related user was set successfully." },
                { "Validation.CompanyRequired", "The company cannot be empty. Please select one." },
                { "Result.ApplyAccountUpdateSuccess", "The account request was updated successfully. Please wait for approval." },
                { "Validation.PasswordMismatch", "The password does not match the confirmation password. Please re-enter." },
                { "Common.UserFullName", "User name" },
                { "Common.RealName", "Full name" },
                { "Validation.InvalidEmail", "The email format is incorrect. Please re-enter." },
                { "Result.ApplyAccountSuccess", "The account was requested successfully. Please wait for approval." },
                { "Confirm.OverwriteExportFile", "The export target file already exists. Overwrite \"{0}\"?" },
                { "Result.SendEmailSuccess", "The email was sent successfully." },
                { "Result.ClearExceptionSuccess", "The exception information was cleared successfully." },
                { "Confirm.ClearException", "Are you sure you want to clear the exception information?" },
                { "Validation.ContentRequired", "Content cannot be empty" },
                { "Result.SendEmailFailed", "Failed to send the email." },
                { "Result.MoveSuccess", "Moved successfully." },
                { "Common.ExceptionReport", "Application exception report" },
                { "File.SelectedDocumentNotExists", "The document you selected does not exist. Please select again." },
                { "Common.NoDataToCopy", "No data to copy!" },
                { "Validation.SelectDataRequired", "Please select the data to process." },
                { "Confirm.NoRejectReason", "Are you sure you want to submit without a return reason?" },
                { "Confirm.CancelWorkflow", "Are you sure you want to revoke this document in the approval workflow?" },
                { "Validation.SelectAuditUser", "Please select the user to submit for approval." },
                { "Confirm.SubmitToUser", "Are you sure you want to submit to user {0} for approval?" },
                { "Workflow.SendSuccess", "The workflow was sent successfully." },
                { "Workflow.SendFailed", "Failed to send the workflow." },
                { "Confirm.ReplaceFile", "Are you sure you want to replace the file {0}?" },
                { "Org.ParentOrganization", "Parent organization" },
                { "Confirm.SaveConfiguration", "The configuration has been modified. Save the changes?" },
                { "Common.NoDataToSave", "No data to save!" },
                { "Org.CompanyName", "Company name" },
                { "Validation.SelectAuditDepartment", "Please select the department to submit for approval." },
                { "Confirm.SubmitToDepartment", "Are you sure you want to submit to department {0} for approval?" },
                { "Validation.SelectAuditRole", "Please select the role to submit for approval." },
                { "Confirm.SubmitToRole", "Are you sure you want to submit to role {0} for approval?" },
                { "Validation.SelectAuditor", "Please select the role, department, or user to submit for approval." },
                { "Workflow.RejectSuccess", "{0} item(s) returned successfully." },
                { "Workflow.RejectFailed", "Failed to return." },
                { "Confirm.ForwardTo", "Are you sure you want to forward to {0} for approval?" },
                { "Workflow.ForwardSuccess", "{0} item(s) forwarded successfully." },
                { "Workflow.ForwardFailed", "Failed to forward." },
                { "Logon.ForcedOfflineByOtherLogin", "Sign-off notice: your account signed in from another location, so you have been signed out." },
                { "Confirm.Save", "Are you sure you want to save?" },
                { "Common.Category", "Category." },
                { "Validation.SelectItem", "Please select {0}." },
                { "Validation.SelectUserOrgOrRole", "You must select one of user, organization, or role." },
                { "Logon.AccountLockedForMinutes", "Your account sign-in is abnormal and has been locked by the system for {0} minutes. Contact the system administrator if you have questions." },
                { "Confirm.ClearPermission", "Are you sure you want to clear the permissions?" },
                { "System.ConnectSuccess", "Successfully connected to the target data source." },
                { "Common.DebugInfo", "Debug information" },
                { "System.AccessDenied", "Access denied: unauthorized access." },
                { "System.ServiceCallDeniedNotSignedIn", "Service call denied: the user is not signed in." },
                { "System.ConfigurationError", "System configuration message error. Please contact the software vendor." },
                { "Confirm.ResetMenu", "Are you sure you want to reset the function menu?" },
                { "Validation.InvalidValue", "{0} is incorrect. Please re-enter." },
                { "Confirm.InitializeSystem", "Are you sure you want to initialize the system?" },
                { "Common.Failed", "The operation failed." },
                { "Logon.PasswordStrengthInsufficient", "The password does not meet the strength requirements. It must be at least 8 characters and combine letters and digits." },
                { "Common.Mobile", "Mobile phone" },
                { "Common.Email", "Email" },
                { "Common.EmployeeNumber", "Employee number" },
                { "Logon.UserNameOrPasswordIncorrect", "Incorrect user name or password" },
                { "System.ServiceNotStarted", "Service not started" },
                { "System.ServiceExpired", "Service expired" },
                { "Common.Value", "Value" },
                { "Org.Company", "Company" },
                { "Org.Department", "Department" },
                { "Logon.EmailNotConfigured", "The user has no email address configured." },
                { "Logon.AccountLockedRetryAfterOneMinute", "The user account is locked. Try again in 1 minute or contact the system administrator." },
                { "Logon.AccountNotActivated", "The user has not activated the account." },
                { "Logon.AccountAlreadyActivated", "The user account has been activated." },
                { "Common.UserRelation", "User association." },
                { "Validation.ConstraintRequired", "Please set the constraint conditions." },
                { "Common.Show", "Show   ▽" },
                { "Common.Hide", "Hide   △" },
                { "Result.ValidateExpressionSuccess", "The expression was validated successfully." },
                { "Validation.ConditionRequired", "Please enter the condition." },
                { "Validation.ContentEmpty", "Please enter the content." },
                { "Validation.MissingLeftBracket", "Missing the ( symbol." },
                { "Validation.MissingRightBracket", "Missing the ) symbol." },
                { "Common.UniqueUserName", "Unique user name" },
                { "Common.Data", "Data" },
                { "Common.NoRecordMatched", "No records found matching the criteria" },
                { "Common.UserName", "User name" },
                { "Validation.DataError", "Data validation error" },
                { "Common.NewPassword", "New password" },
                { "Common.ConfirmPassword", "Confirm password" },
                { "Common.OldPassword", "Current password" },
                { "Result.ModifySuccess", "{0} changed successfully." },
                { "Result.SetSuccess", "{0} set successfully." },
                { "Common.Password", "Password" },
                { "Result.ExecuteSuccess", "Executed successfully." },
                { "Logon.UserNotFoundCaseSensitive", "User not found. Please check the letter case." },
                { "Logon.PasswordIncorrectCaseSensitive", "Incorrect password. Please check the letter case." },
                { "Logon.AccountDisabled", "Sign-in denied: the account is disabled. Please contact the system administrator." },
                { "Common.BaseCode", "Base code" },
                { "Org.Employee", "Staff" },
                { "Org.Organization", "Organization" },
                { "Org.Role", "Role" },
                { "Common.Menu", "Menu" },
                { "Common.Folder", "Folder" },
                { "Common.Permission", "Permission" },
                { "Common.PrimaryKey", "Primary key" },
                { "Common.Code", "Code" },
                { "Common.Name", "Name" },
                { "Common.ParentId", "Parent id" },
                { "Common.ParentName", "Parent name" },
                { "Common.FunctionCategoryId", "Category id" },
                { "Common.UniqueId", "Unique id" },
                { "Common.Subject", "Subject" },
                { "Common.Content", "Content" },
                { "Common.StatusCode", "Status code" },
                { "Common.Times", "Count" },
                { "Common.Enabled", "Enabled" },
                { "Common.Remark", "Remark" },
                { "Common.SortCode", "Sort code" },
                { "Common.CreatedBy", "Created by" },
                { "Common.CreatedOn", "Created on" },
                { "Common.ModifiedBy", "Modified by" },
                { "Common.ModifiedOn", "Modified on" },
                { "Common.Sort", "Sort" },
                { "Common.Index", "Index" },
                { "Common.Field", "Field" },
                { "Common.Table", "Table" },
                { "Common.Database", "Database" },
                { "Logon.Relogin", "Sign in again" },
                { "Validation.SelectAtLeastOneItem", "Please select at least one item." },
                { "Validation.SelectOnlyOne", "Only one record can be selected." },
                { "Sign.PrivateKey", "Signature private key." },
                { "Sign.Password", "Signature password." },
                { "Sign.CommunicationUserName", "Communication user name." },
                { "Sign.CommunicationPassword", "Communication password." },
                { "Sign.VerificationCode", "Verification code" },

                // 枚举描述（键格式 Enum.<类型>.<成员>，与 Status.cs / AuditStatus.cs 一一对应）
                { "Enum.Status.SystemCodeError", "Invalid system code; sign-in blocked" },
                { "Enum.Status.AccessDeny", "Unauthorized access; access blocked" },
                { "Enum.Status.DbError", "Database connection error" },
                { "Enum.Status.UserOnline", "User is already online" },
                { "Enum.Status.UserNotLogin", "User is not signed in" },
                { "Enum.Status.MissingData", "Missing user sign-in data" },
                { "Enum.Status.Error", "An error occurred" },
                { "Enum.Status.Ok", "Operation succeeded" },
                { "Enum.Status.OkAdd", "Added successfully" },
                { "Enum.Status.CanNotLock", "Unable to lock the data" },
                { "Enum.Status.LockOk", "Data locked successfully" },
                { "Enum.Status.OkUpdate", "Updated successfully" },
                { "Enum.Status.OkDelete", "Deleted successfully" },
                { "Enum.Status.Exist", "The data already exists; duplicates are not allowed" },
                { "Enum.Status.ErrorCodeExist", "The code already exists; duplicates are not allowed" },
                { "Enum.Status.ErrorNameExist", "The name already exists" },
                { "Enum.Status.ErrorValueExist", "The value already exists" },
                { "Enum.Status.ErrorUserExist", "The user name already exists" },
                { "Enum.Status.OkOperation", "Completed successfully" },
                { "Enum.Status.ErrorDataRelated", "The data is referenced by related records" },
                { "Enum.Status.ErrorDeleted", "The data has been deleted by someone else" },
                { "Enum.Status.ErrorUpdate", "Failed to update the data" },
                { "Enum.Status.ErrorChanged", "The data has been modified by someone else" },
                { "Enum.Status.NotFound", "Record not found" },
                { "Enum.Status.UserNotFound", "User not found" },
                { "Enum.Status.PasswordError", "Incorrect password" },
                { "Enum.Status.LogonDeny", "Sign-in denied" },
                { "Enum.Status.ErrorOnline", "Only one concurrent sign-in is allowed" },
                { "Enum.Status.ErrorMacAddress", "Invalid MAC address; sign-in blocked" },
                { "Enum.Status.ErrorIpAddress", "Invalid IP address; sign-in blocked" },
                { "Enum.Status.ErrorOnlineLimit", "Concurrent user limit reached" },
                { "Enum.Status.PasswordCanNotBeNull", "Password cannot be empty" },
                { "Enum.Status.PasswordCanNotBeRepeat", "Password cannot be reused" },
                { "Enum.Status.SetPasswordOk", "Password set successfully" },
                { "Enum.Status.OldPasswordError", "Current password is incorrect" },
                { "Enum.Status.ChangePasswordOk", "Password changed successfully" },
                { "Enum.Status.UserNotEmail", "No email address" },
                { "Enum.Status.UserLocked", "Locked" },
                { "Enum.Status.UserNotActive", "User is not activated" },
                { "Enum.Status.UserIsActivate", "User is already activated" },
                { "Enum.Status.ErrorLogon", "Incorrect user name or password; for security reasons the exact reason is not disclosed" },
                { "Enum.Status.WaitForAudit", "Pending review" },
                { "Enum.Status.UserDuplicate", "Duplicate user name" },
                { "Enum.Status.UserLogon", "User sign-in" },
                { "Enum.Status.Timeout", "Session timed out; please sign in again" },
                { "Enum.Status.ChangePassword", "Change password" },
                { "Enum.Status.WeakPassword", "Password does not meet the policy" },
                { "Enum.Status.UserNotMobile", "No mobile number" },
                { "Enum.Status.IpLimit", "Access restricted due to frequent operations" },
                { "Enum.Status.LogonLimit", "Sign-in restricted due to frequent attempts" },
                { "Enum.Status.UserNameLimit", "Sign-in restricted: user name tried too frequently" },
                { "Enum.Status.PasswordLimit", "Sign-in restricted: password tried too frequently" },
                { "Enum.Status.ServiceNotStart", "Service has not started" },
                { "Enum.Status.ServiceExpired", "Service expired" },
                { "Enum.Status.ParameterError", "Parameter error" },
                { "Enum.Status.NotAllowEdit", "Editing is not allowed" },
                { "Enum.Status.SignOut", "Signed out" },
                { "Enum.Status.CompanyNotFound", "Company not found" },
                { "Enum.Status.VerificationCodeError", "Incorrect verification code" },
                { "Enum.Status.SignatureError", "Data tampered with; network hijacked" },
                { "Enum.AuditStatus.Pause", "Paused" },
                { "Enum.AuditStatus.Draft", "Draft" },
                { "Enum.AuditStatus.StartAudit", "Submitted" },
                { "Enum.AuditStatus.AuditPass", "Approved" },
                { "Enum.AuditStatus.WaitForAudit", "Pending" },
                { "Enum.AuditStatus.Transmit", "Forwarded" },
                { "Enum.AuditStatus.AuditReject", "Rejected" },
                { "Enum.AuditStatus.AuditComplete", "Completed" },
                { "Enum.AuditStatus.AuditQuash", "Discarded" },
                { "Enum.AuditStatus.AuditAccept", "Accepted" },

                // 异常消息与业务状态消息（异常 11 + 结果/登录 5）
                { "Exception.NoWritePermission", "The current OS user has no permission to write file {0}" },
                { "Exception.GenericNotSupported", "Generic types are not supported; a concrete entity class is required" },
                { "Exception.ExpressionIllegalChar", "The expression contains illegal characters." },
                { "Exception.ExpressionEmpty", "The expression cannot be empty." },
                { "Exception.ExpressionSyntaxError", "Expression syntax error." },
                { "Exception.DivideByZero", "The divisor cannot be zero." },
                { "Exception.BracketMismatch", "Brackets do not match." },
                { "Exception.ExpressionIllegalNumber", "The expression contains an illegal number." },
                { "Exception.FileNotFound", "File {0} does not exist!" },
                { "Exception.BackupFileNotFound", "File {0} does not exist! Unable to back up this file!" },
                { "Exception.InvalidIp", "Invalid IP" },
                { "Result.UnknownError", "Unknown error" },
                { "Logon.Success", "Sign-in succeeded" },
                { "Logon.AccessDeniedAdmin", "Access denied: your account has no back-office administration permission." },
                { "Logon.AccessDenied", "Access denied: your account has no access permission." },
                { "Logon.RequireUniqueUserName", "Please sign in with a unique user name; if you do not know it, ask your company administrator." },

                // ===== 日志消息 =====
                { "Log.AddLogTaskFailedWithUser", "AddLogTask: Exception: {0}userName:{1}{2}Source: {3}{2}Stack trace: {4}" },
                { "Log.AddLogTaskFailed", "AddLogTask: Exception: {0}{1}Source: {2}{1}Stack trace: {3}" },
                { "Log.SaveEntityChangeLogTypeMismatch", "The compared entity types differ, or the type is not an entity type" },
                { "Log.ServiceFail", "Service invocation failed, please check: {0}" },
                { "Log.ConfigParseFailed", "UserConfigUtil failed to parse configuration: {0}={1}. The default value is used." },
                { "Log.DisposeMemberFailed", "Dispose failed to release the member object: {0}" },
                { "Log.DisposeFailed", "Dispose failed to release the object: {0}" },
                { "Log.GetSourceTextByUrlFailed", "GetSourceTextByUrl failed to retrieve URL content: {0}" },
                { "Log.RestartIisFailed", "RestartIisProcess failed to rewrite web.config" },
                { "Log.RemoteSaveAsFailed", "RemoteSaveAs failed to download the remote file: {0}" },
                { "Log.TemplateFileNotFound", "Template file not found" },
                { "Log.OpenTemplateFailed", "Failed to open the template file" },

                // ===== 控制台输出 =====
                { "Console.Completed", "{0} : done " },
                { "Console.OcrGeneral", "General text recognition:" },
                { "Console.ParallelTaskStart", "Parallel task {0} starting..." },
                { "Console.TaskStart", "Task {0} starting..." },

                // ===== AppMessage.Service 功能名常量 =====
                { "Service.FileService", "Archive service" },
                { "Service.FileServiceSystemCreateDirectory", "System created directory" },
                { "Service.FileServiceCompanyFile", "Company documents" },
                { "Service.FileServiceShareFolder", "Shared documents" },
                { "Service.FileServiceUserSpace", "User space" },
                { "Service.FileServiceFolder", "'s folder" },
                { "Service.FileServiceSendFile", "Sent files" },
                { "Service.FileServiceFile", "'s files" },
                { "Service.FileServiceReceiveFile", "Received files" },
                { "Service.FileServiceSendFileFrom", " sent file " },
                { "Service.FileServiceCheckReceiveFile", ", please check and acknowledge." },
                { "Service.FileServiceGetEntity", "Get entity" },
                { "Service.FileServiceExists", "Check existence" },
                { "Service.FileServiceDownload", "Download file" },
                { "Service.FileServiceUpload", "Upload archive" },
                { "Service.FileServiceGetDataTableByFolder", "Get archive list by folder" },
                { "Service.FileServiceGetDataTableByIds", "Get archive list by file ID" },
                { "Service.FileServiceDeleteByFolder", "Delete archives by folder" },
                { "Service.UserService", "User management service" },
                { "Service.UserServiceCheck", "Please review." },
                { "Service.UserServiceApplication", " applied for an account: " },
                { "Service.UserServiceAddUser", "Add user" },
                { "Service.UserServiceGetDataTableByDepartment", "Get user list by department" },
                { "Service.UserServiceGetEntity", "Get entity" },
                { "Service.UserServiceGetDataTable", "Get list" },
                { "Service.UserServiceGetDataTableByRole", "Get list by role" },
                { "Service.UserServiceGetDataTableByIds", "Get list by ID" },
                { "Service.UserServiceGetRoleDataTable", "Get the role list of the user" },
                { "Service.UserServiceUserInRole", "Check whether the user is in a role" },
                { "Service.UserServiceUpdateUser", "Update user" },
                { "Service.UserServiceSearch", "Search users" },
                { "Service.UserServiceSetUserAuditStates", "Set user audit status" },
                { "Service.UserServiceSetDefaultRole", "Set the default role of the user" },

                // ===== 补漏：登录状态消息（P5）=====
                { "Logon.UserNotFound", "The corresponding user was not found" },
                { "Logon.PasswordResetMailSent", "The new password has been sent to your registered mailbox {0}, please check it." },
                { "Logon.UpdateDatabaseFailed", "Failed to update the database, please retry!" },
                { "Logon.UserLockedCannotResetPassword", "The user is locked; resetting the password is not allowed." },
                { "Logon.UserNotFoundRetry", "User not found, please re-enter the user name." },
                { "Logon.UserLockedCannotSetPassword", "The user is locked; setting a password is not allowed." },
                { "Logon.UserNotActivated", "The user is not activated yet; setting a password is not allowed." },
                { "Logon.AppUserNotFound", "The application system user does not exist, please contact the administrator." },
                { "Logon.DomainServerResponse", "Domain server returned: {0}" },
                { "Logon.Failed", "Sign-in failed" },

                // ===== 补漏：业务操作错误消息（P5）=====
                { "Business.DataAlreadyDeleted", "The data has already been deleted; there is no need to delete it again" },
                { "Business.DataNotDeleted", "The data has not been deleted; there is no need to undo" },
                { "Business.DataAlreadyEnabled", "The data is already enabled; there is no need to enable it again" },
                { "Business.DataAlreadyDisabled", "The data is already disabled; there is no need to disable it again" },
                { "Business.SystemDataNoPermission", "No permission to operate on system data" },
                { "Business.OtherCompanyDataNoPermission", "No permission to operate on data of another company" },

                // ===== 补漏：工具类返回消息（P5）=====
                { "Rmb.Overflow", "Overflow" },
                { "Rmb.NotNumeric", "Not a numeric value!" },
                { "Qqwry.Unknown", "Unknown" },
                { "Sms.InvalidMobile", "Invalid mobile number!" }
            };
        }
    }
}
